### ISSUE TITLE
リレーを登録してほしい

### ISSUE THREAD

**Issue by 1inguini** [pasokonistan/pasokey.net#4]
デカいリレーとしてはhttps://relay.toot.yukimochi.jp があったり、VRChatter向けサーバーを集めたhttps://relay.virtualkemomimi.net とかもある

**Comment by sksat** [comment]
https://relay.toot.yukimochi.jp は色々と信頼しているのでアリです．
ただ，特段「VRChatとかNeosVRとかClusterとか」を意図したサービスではないので，後者は違いそう．

**Comment by 1inguini** [comment]
登録するとますみすサーチというサービスで検索可能にできるリレーもある
https://masmis-search.ja-jp.org/ui/relay
