### ISSUE TITLE
13.11.3に更新

### ISSUE THREAD

**Issue by 1inguini** [pasokonistan/pasokey.net#7]

**Comment by sksat** [comment]
更新すること自体はやぶさかではないのですが，[13.11.0](https://github.com/misskey-dev/misskey/releases/tag/13.11.0) 以降，通知が Redis に保存されるようになる（揮発するようになる）ので，redis pod の永続化をしてからやりたいなと思っているのと，単に既存の通知が一気に消えてしまうので躊躇しているという事情があります．

それはそれとして，これは愚痴というよりは一般的なアドバイスなのですが，自分がオーナーのリポジトリでもなければ，Issue にはある程度詳細を書いた方がよいです．

**Comment by sksat** [comment]
resolved in #11
