### ISSUE TITLE
同意のリアクションが欲しい

### ISSUE THREAD

**Issue by 1inguini** [pasokonistan/pasokey.net#9]
同意をリアクションで表したいことは多くあるが、デフォルトの絵文字には適したものがない。わかり哲也([例](https://twitter.com/1amr_/status/898954048635678720?t=bvCXgoORMfuousamP20WWg&s=19))か何かを追加してほしい。

**Comment by sksat** [comment]
わかり哲也は権利的にナシかな（リアクションの絵文字は外部に配信されるため）

**Comment by 1inguini** [comment]
平仮名で「わかる」とか「そう」とか書かれてるだけのやつでもいいのでほしい

**Comment by sksat** [comment]
入れたくないわけではないが，提案が曖昧なので閉じ
